In [1]:
!pip install tensorflow


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

In [3]:
data = pd.read_csv('iris.csv')

In [4]:
print(data.head())

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa


In [5]:
# Podział danych na cechy (features) i etykiety (labels)
X = data[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']].values
y = data['variety'].values

In [6]:
# Zakodowanie etykiet do postaci numerycznej
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

# Konwersja etykiet do postaci one-hot
y_categorical = to_categorical(y_encoded)

In [7]:
# Podział danych na zbiór treningowy i testowy
X_train, X_test, y_train, y_test = train_test_split(X, y_categorical, test_size=0.2, random_state=42)

In [8]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, input_shape=(4,), activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')])

C:\Users\Wojciech\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
# Kompilacja modelu
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [10]:
# Wyświetlenie podsumowania modelu
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │              50 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 3)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 193 (772.00 B)

 Trainable params: 193 (772.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
# Trenowanie modelu
history = model.fit(X_train, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 120ms/step - accuracy: 0.3294 - loss: 1.2279 - val_accuracy: 0.5417 - val_loss: 1.0894
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5690 - loss: 1.1428 - val_accuracy: 0.6667 - val_loss: 1.0197
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.4896 - loss: 1.1107 - val_accuracy: 0.6667 - val_loss: 0.9685
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5260 - loss: 1.0707 - val_accuracy: 0.6667 - val_loss: 0.9286
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5911 - loss: 1.0076 - val_accuracy: 0.7083 - val_loss: 0.8958
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6211 - loss: 0.9743 - val_accuracy: 0.7083 - val_loss: 0.8720
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5990 - loss: 0.9439 - val_accuracy: 0.7083 - val_loss: 0.8540
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6341 - loss: 0.8964 - val_accuracy: 0.7083 - val_loss

In [12]:
# Ocena modelu na danych testowych
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_accuracy}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 1.0000 - loss: 0.2765
Test accuracy: 1.0


In [13]:
predictions = model.predict(X_test)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
[[8.8862181e-03 6.3493800e-01 3.5617581e-01]
 [9.9180555e-01 7.9825288e-03 2.1192947e-04]
 [5.6953795e-05 1.5484780e-01 8.4509522e-01]
 [7.7342591e-03 6.1910790e-01 3.7315783e-01]
 [1.0271545e-02 7.0746237e-01 2.8226608e-01]
 [9.8961276e-01 1.0070200e-02 3.1694799e-04]
 [5.0173283e-02 7.5409961e-01 1.9572710e-01]
 [1.5569156e-03 4.7776496e-01 5.2067822e-01]
 [8.1770299e-03 5.9690344e-01 3.9491957e-01]
 [3.0572750e-02 7.6045024e-01 2.0897698e-01]
 [1.7066697e-03 4.6348140e-01 5.3481197e-01]
 [9.8775035e-01 1.1806681e-02 4.4300730e-04]
 [9.9588341e-01 4.0299883e-03 8.6580381e-05]
 [9.8660606e-01 1.2911928e-02 4.8196298e-04]
 [9.8962992e-01 1.0023650e-02 3.4636148e-04]
 [6.3715661e-03 6.4065862e-01 3.5296980e-01]
 [2.0316505e-04 2.1199410e-01 7.8780276e-01]
 [2.9061044e-02 7.3151642e-01 2.3942256e-01]
 [7.7300863e-03 5.8695763e-01 4.0531230e-01]
 [2.7595356e-04 2.2651690e-01 7.7320719e-01]
 [9.7580987e-01 2.3055429e-02 1.1347629e-03]
 [2.2830206e-03 4